### ISSUE TITLE
Component update issue

### ISSUE THREAD

**Issue by elenabraeutigam** [divriots/story-to-design#102]
## Describe the problem ##
Sometimes, when a previously "damaged" component has a new update available, the preview in the plugin will visualize the component correctly, but after updating it the component is still damaged in the Figma canvas.
Below is an example for the sidebar component:

As you can see in the screenshot, in our sidebar component, we had the issue that the profile picture was distorted. According to the preview in story.to.design the issue should be fixed for the updated component:
<img width="885" alt="image1" src="https://github.com/divriots/story-to-design/assets/129752452/e645e110-2203-4c30-9ba2-50f5914fadca">

But after updating, the profile picture was still wrong in the Figma canvas:
<img width="884" alt="image2" src="https://github.com/divriots/story-to-design/assets/129752452/a228c751-222f-4fb6-85cd-bb4c0bf9641f">

I tried resetting the canvas, reprocessing the story and also removing the component and reimporting it, but nothing worked.

---
Bug report identity: Please do not edit

Sidebar
Task path: 3ha6WtaKf2ON2Bf0HK24/MUBFy0fU4d2iUBLSF2tU/1nqrlsx1kuqjdv

Avatar#1 
Task path: 3ha6WtaKf2ON2Bf0HK24/MUBFy0fU4d2iUBLSF2tU/6ycfiabre0cg

Avatar#2
Task path: 3ha6WtaKf2ON2Bf0HK24/00f7m128hXRSLVRE1i2O/ablztz89vg3x

**Comment by gqio** [comment]
Hello @elenabraeutigam 

Is this icon is coming from an outdated subcomponent ? like Icon button, Icon, Link ?

We don't do any subcomponent detection or linking while diffing, it would be too much expansive in term of computing.
That's why there is a diff here.

Could you please also report the icon (maybe the Link component) that way I can have a look.

Best.

**Comment by elenabraeutigam** [comment]
We use the Avatar component there.
Here's the issue link:
https://github.com/divriots/story-to-design/issues/103

**Comment by gqio** [comment]
Hello @elenabraeutigam 

Are you sure it's the Avatar, because the reported one contains only 
![image](https://github.com/divriots/story-to-design/assets/1063530/c0a3aa5e-c257-4ad7-ad59-82e12a1ffef3)

And I need a variant at least looking like this to match the subcomponent detection.
![image](https://github.com/divriots/story-to-design/assets/1063530/7b88ef87-b045-4cd2-a72c-bb7b818a3b6c)

Maybe there is missing variant in the reported Avatar.
You can contact me also in Discord if you need more detailed explanation

Best

**Comment by elenabraeutigam** [comment]
When I select the item in the sidebar component, it says Avatar in the left menu:

<img width="1150" alt="sidebar" src="https://github.com/divriots/story-to-design/assets/129752452/4070dfaa-bb1a-4eb1-8b0e-5b6b26f8bd92">


When I click on "Go to main component", it redirects me to the Avatar component:

<img width="977" alt="avatar" src="https://github.com/divriots/story-to-design/assets/129752452/0f2cb8a0-a4f0-421e-b61c-307e771d4460">


I'm noticing right now that it links to the Avatar-Source component. Perhaps I reported the wrong Avatar story via the plugin. Both stories don't have any variants though with the logo that is used in the Sidebar component.

**Comment by elenabraeutigam** [comment]
https://github.com/divriots/story-to-design/issues/105

**Comment by gqio** [comment]
this one should be fixed with the latest version of the plugin + agent

Best
