### ISSUE TITLE
Content doesn't resize with container

### ISSUE THREAD

**Issue by alexandergrot** [divriots/story-to-design#107]
hey all,
we have a stepper component, which when imported doesn't change the contents size if the outer container is resized. see this screenshot: 
![grafik](https://github.com/divriots/story-to-design/assets/102791744/d6dce593-47ef-418f-ae9c-c8474f76247c)

---
Bug report identity: Please do not edit

Task path: 3ha6WtaKf2ON2Bf0HK24/cTJHZkeCJCNZ1kgqi46Q/19nwc8r1fkw5wd

**Comment by gqio** [comment]
Hello @alexandergrot 

Normally we support resize out of the box but here if we try to reduce the stepper to fit content, then the connector disappear, and because we need to know which size should take the component in case of block component, Otherwise we cannot capture an element with 0 width.
Now with the new version you can specify a `viewport` for importing a full width component

here is the configuration you can use in the plugin 
![image](https://github.com/divriots/story-to-design/assets/1063530/f482edd3-d9f1-4195-8c27-319435f60d8b)

and here the component fixed
![image](https://github.com/divriots/story-to-design/assets/1063530/99f951cf-092c-4c35-87fd-5b6c8c49df57)

Please report a new component if I missed something.

Best.
