### ISSUE TITLE
Unwanted component resizing

### ISSUE THREAD

**Issue by elenabraeutigam** [divriots/story-to-design#109]
## Describe the problem ##
The Alert component is resized via the plugin even though this does not match our Storybook:
<img width="1346" alt="Screenshot 2023-09-13 at 13 35 44" src="https://github.com/divriots/story-to-design/assets/129752452/939f226a-b8e3-440e-8960-e08b615e2cb2">
<img width="268" alt="Screenshot 2023-09-13 at 14 13 24" src="https://github.com/divriots/story-to-design/assets/129752452/a6e6d060-7cea-4cf4-bf93-a00cee5da920">

---
Bug report identity: Please do not edit

Task path: 3ha6WtaKf2ON2Bf0HK24/4yliGsRsjDiI50BV9Add/1eb5awr16abfj8

**Comment by gqio** [comment]
Hello @elenabraeutigam 

Starting from now, story.to.design have a new property called viewport telling to s2d what would be the width of the rendering for full width component (like alert).
Because we can't know if the component is an inline component (deep nested inside some block wrappers) or it's a full width component that display some stuff on a particular viewport.

By default all component will be used as fit-content, but when specify the viewport we take into account the rendering of this width while capturing the component.

You can find this property here when you edit the component
![image](https://github.com/divriots/story-to-design/assets/1063530/c9b73c21-0613-4831-92fc-205e91db6691)

You should not see anymore this diff between 2 updates with those weird resizes.

Best.

**Comment by elenabraeutigam** [comment]
Hello @gqio 

Thanks. One more question regarding the viewport property: Does this mean that it would be best practice to set at least one (default) viewport for each Story? Or should this property only be selected for Stories / components when they are full width?

**Comment by gqio** [comment]
Hello @elenabraeutigam 

As far as I can tell you might to specify a viewport only for components that has a full width variant.

We would love to have your feedback once setup with your components.

Best
