### ISSUE TITLE
New component issue report

### ISSUE THREAD

**Issue by pancheisor** [divriots/story-to-design#120]
## Describe the problem ##

---
Bug report identity: Please do not edit

Task path: ObILdV0S820TPTLWYtEm/NYlgwqNBu5wLqQ7EpsM7/roacy0al3l8k

**Comment by gqio** [comment]
Hello @pancheisor 

Before digging into this could you please let us know what we should have a look and what is not expected or incorrect ? Maybe a screenshot ?
It will help us a lot to have a look into your issue.

Best.
Greg.

**Comment by muryoh** [comment]
I imagine the problem to be the missing autolayout on the tertiary variant:
![image](https://github.com/divriots/story-to-design/assets/1789748/4e117aae-f3f5-4d04-8748-91895ad4d4e8)

But it would be nice if you could confirm @pancheisor 

Cheers

**Comment by muryoh** [comment]
The problem is that the font size renders slightly differently in Figma than it does in Chromium
In Chromium:
![image](https://github.com/divriots/story-to-design/assets/1789748/27d3ddae-cd90-47f7-a8e9-cfd206ba8db8)
In Figma
![image](https://github.com/divriots/story-to-design/assets/1789748/126266ee-129b-4854-9a56-3aa3c17984df)

So 68.03px vs 69px for the text
The expected button size is 68.03px: if we autolayout it, since the text is larger than expected, we'd have to resize the button too
 
We currently dont take the liberty to do that but we could
