### ISSUE TITLE
New component issue report

### ISSUE THREAD

**Issue by sophie1620** [divriots/story-to-design#122]
## Describe the problem ##

I'm testing story.to.design, but I've not been able to see my component's variants.  They are all showing as 'ERROR'.

Additionally, I cannot remove my components.  

Connecting and selecting arguments for variants:
![Screenshot 2023-10-30 at 11 03 08 AM](https://github.com/divriots/story-to-design/assets/36078581/fe0de930-7e02-495d-934b-a1bd066b0ed2)

The errors:
![Screenshot 2023-10-30 at 11 03 37 AM](https://github.com/divriots/story-to-design/assets/36078581/568dacf5-2002-407b-8f90-f6e0a8e8e641)

What my component looks like on Storybook:
![Screenshot 2023-10-30 at 11 43 11 AM](https://github.com/divriots/story-to-design/assets/36078581/a649bbd1-8563-43d3-818b-a2d44da20e53)

No components imported, but still showing I've reached the limit for testing on a free account:
![Screenshot 2023-10-30 at 11 44 58 AM](https://github.com/divriots/story-to-design/assets/36078581/a1e03739-cab6-427a-ba84-7fef80fd881a)

---
Bug report identity: Please do not edit

Task path: 9TBqtTjmCWYLv11mEwhT/GC9PQpUnR5GcxpJdizzy/1iw3pcf17i9j7d

**Comment by gqio** [comment]
Hello @sophie1620 

I just checked and apparently you are using an angular app.

Basically what story.to.design does is waiting for the first child to be rendered on the storybook-root
Here the render is done in two pass, first the app is rendered and then the component is renderered.

The fact nothing is rendered or in error is because story.to.design cannot guess what is the correct component to capture.
We have an advanced configuration for that
https://story.to.design/docs/setup-variants-advanced

And more specifically this one https://story.to.design/docs/special-args

That way you can configure what story.to.design should consider inside your storybook-root as the component you want to extract.

![image](https://github.com/divriots/story-to-design/assets/1063530/091595ff-3e11-49da-8aaa-e6ba8fd43903)

That way you can end up with this with pretty much small configuration. I can help you on that part.

![image](https://github.com/divriots/story-to-design/assets/1063530/7af11d1b-f262-48d3-959d-430cb7769a63)

And now you can use your component inside Figma with all the props you need

![image](https://github.com/divriots/story-to-design/assets/1063530/23123864-b31e-49db-ab22-09f5b85a5004)


Best.

Greg.

PS: I reseted you import component count to 0.
PS2: don't hesitate to reach us on https://story.to.design/chat for more details and support

**Comment by muryoh** [comment]
Closing as it looks like Greg's configuration fixed it
Cheers
Remy
