### ISSUE TITLE
Pulling in a fresh Breadcrumb from Fluent with zero changes has a lot of issues.

### ISSUE THREAD

**Issue by Counsell1111** [divriots/story-to-design#126]
## Describe the problem ##

---  So we're building a design system on top of Fluent UI and none of the components seem to be all that usable within Figma. 

Here's the Breadcrumb from Fluent, no changes have been made to either the markup or the CSS, this is a bare-bones version of the standard Fluent Breadcrumb and here are a few issues keeping it from being usable within Figma.

• The secondary items ignore space when a longer value is entered.
![image](https://github.com/divriots/story-to-design/assets/130077304/2a2b2a41-ac97-4916-b0c9-80d591b63aac)

•There's no way to change properties on the individual / secondary breadcrumb items.

• When changing values I need to click pretty deep into the component.

Bug report identity: Please do not edit

Task path: H5wicg5xvN61lpBgxzah/3NKrCZWygCYQfkbIyx0Z/158re7f162tvv1

**Comment by gqio** [comment]
Hello @Counsell1111 

> • The secondary items ignore space when a longer value is entered.

This issue is related to Figma that cannot render exactly the same size of the Text between Figma and browser. Leading us to not activating the auto layout at this level. We are looking into it but I think it's the same issue linked to the button one.

No auto layout here
![image](https://github.com/divriots/story-to-design/assets/1063530/32e16d41-03be-465b-8f49-e1ccb71b0b1c)

Due to this text slightly bigger in width than expected.
![image](https://github.com/divriots/story-to-design/assets/1063530/67a030d0-9c07-4f78-9437-7991d01e05ba)


> •There's no way to change properties on the individual / secondary breadcrumb items.

Not sure what do you mean here. Could you please give me an example on what you are trying to do ?
If you are looking into modifying via properties the values inside the breadcrumb you need to expose how we should parse these properties. either via storybook api or with our advanced variant properties api https://story.to.design/docs/variant-properties-api . I can help here. Please advise what you would like to see in Figma.

> • When changing values I need to click pretty deep into the component.

I guess you mean these 3 levels ?

![image](https://github.com/divriots/story-to-design/assets/1063530/6ef0182c-967e-4c3f-a8f0-aea16117f27c)

I think we could try to remove 1 level from those 3 but not much since the container of the breadcrumbs need to be here, and we need also a container(the button) around the text since this button has padding.

Best.

**Comment by gqio** [comment]
Closing it since this issue is the same as the button issue you experienced and Remy is already on it.

**Comment by muryoh** [comment]
I confirm that with the work in progress for https://github.com/divriots/story-to-design/issues/132, the result looks way nicer:
![image](https://github.com/divriots/story-to-design/assets/1789748/cec7183a-15cd-4841-aae9-ff684b38b77e)
