### ISSUE TITLE
bare-bones Fluent dropdown doesn't have any properties and can't be scaled.

### ISSUE THREAD

**Issue by Counsell1111** [divriots/story-to-design#127]
## Describe the problem ##

---  So we're building a design system on top of Fluent UI and none of the components seem to be all that usable within Figma.

Here's the Dropdown from Fluent, no changes have been made to either the markup or the CSS, this is a bare-bones version of the standard Fluent Dropdown and here are a few issues keeping it from being usable within Figma.

• Component isn't scaleable, we can't decrease or increase the width of component.
![Screenshot 2024-01-10 at 6 11 46 PM](https://github.com/divriots/story-to-design/assets/130077304/560ee195-fb39-49b3-b710-61dd7a45a78d)
![Screenshot 2024-01-10 at 6 09 47 PM](https://github.com/divriots/story-to-design/assets/130077304/15c649d8-d123-4907-b90c-edd78e7fb5c0)
• Component doesn't appear to have any available properties even though the story has plenty of args.
• Component doesn't have the ability to edit the Value, placeholder or the title text.
• Can't change the state of the component.

Bug report identity: Please do not edit

Task path: H5wicg5xvN61lpBgxzah/3NKrCZWygCYQfkbIyx0Z/1vjz6rtxr0xxu

**Comment by gqio** [comment]
Hello @Counsell1111 

> • Component doesn't appear to have any available properties even though the story has plenty of args.

It really depends on how the story is coded.
I checked on the storybook https://master--628d031b55e942004ac95df1.chromatic.com/?path=/docs/components-dropdown--default (the official one)

And it appears there is some args available here.

![image](https://github.com/divriots/story-to-design/assets/1063530/c8034dde-b109-47c6-bb27-b49582e2308e)

Not sure how you wrapped the story on your side I would need to see the code of the story to determine why you lost the args in the process.

> • Component doesn't have the ability to edit the Value, placeholder or the title text.

If this is not exposed as a text value then we cannot map this text as property for variant, because it can be some random text. Here our advanced variants api can help and also I can help here.

> • Can't change the state of the component.

You can do this either via a property if exposed or by acting on the component via our advanced variants api where you can target an action selector https://story.to.design/docs/special-args#actionselector

> • Component isn't scaleable, we can't decrease or increase the width of component.

I need to check why the dropdown is not acting as a hug element here and with a min/max width as defined in the storybook of fluent API. Apparently because some sizing of the text.

But if you look at the component itself it's not a full block element because it's a child of a grid with a justify-items=start, therefore the component will not resize based on the size of the parent, but only with its content.

![image](https://github.com/divriots/story-to-design/assets/1063530/fac7df02-7a11-4c33-98af-9a9ab9757ea4)

I will keep you posted about the text sizing here.

**Comment by gqio** [comment]
Hello @Counsell1111 

We made a lot of fixes around autolayout and resizing. All should be fixed now.
Please reopen another ticket if you see some other issue.

Best.
