### ISSUE TITLE
Fluent tabs list component can't edit values in Figma properties or change states for individual tabs.

### ISSUE THREAD

**Issue by Counsell1111** [divriots/story-to-design#131]
## Fluent tab list component properties and states for individual tabs aren't available ##

Here's the tabs list component from Fluent, no changes have been made to either the markup or the CSS, this is a bare-bones version of the standard Fluent tab list and here are a few issues keeping it from being usable within Figma.

• Individual tabs don't allow the ability to edit individual tab values within Figma properties.
• No ability to add or remove tabs (might not be a possibility).
• Can't switch around tabs or change individual tab states.

---
Bug report identity: Please do not edit

Task path: H5wicg5xvN61lpBgxzah/3NKrCZWygCYQfkbIyx0Z/zv60crz8md8i

**Comment by gqio** [comment]
Hello @Counsell1111 

> • Individual tabs don't allow the ability to edit individual tab values within Figma properties.

Should be exposed in story via args

> • No ability to add or remove tabs (might not be a possibility).

This is not possible directly via Figma ... maybe with some states and variables and with prototypes but not as easy as it seems

> • Can't switch around tabs or change individual tab states.

States should be exposed for each variant, otherwise Figma does not know how to layout which tab is selected or not.
Or alternatively tab list items should be paramterized via variables

With the official storybook fluent UI and config for variant properties

```json
{
  "initArgs": {
    ":selector": "#root > div > div > div", // remove all unecessary extra layer
    ":actionSelector": "button[role='tab']" // I want to click only on the first button with a role tab
  },
  "variantProperties": [
    ":tap" // make 2 variants with clicked and not clicked on the action selector above
  ]
}
```

https://github.com/divriots/story-to-design/assets/1063530/8ae0213d-e619-415a-8eab-61b8a7e602b5


Best
