### ISSUE TITLE
Distorted appearance and text rendering in 100% width style components

### ISSUE THREAD

**Issue by kimkisol** [divriots/story-to-design#134]
## Describe the problem ##

[Distorted appearance and text rendering in 100% width style components]
When importing components with 100% width, they appear distorted, and the text inside is rendered improperly. 
Is there a way to specify the size of the container frame when importing such components? 
Additionally, is there a method to import components' text with Auto Width instead of Auto Height to prevent text distortion?
![스크린샷 2024-01-31 오후 2 15 55](https://github.com/divriots/story-to-design/assets/79404348/9079ab0c-198f-4478-aefc-80ea0e7fb599)

---
Bug report identity: Please do not edit

Task path: FvzdyyFloVER6G2wDlgC/C9SbU9ENutaxDMPjnwCp/4fu68w18iqp8v

**Comment by muryoh** [comment]
Hi @kimkisol ,

This is unexpected, I'm having a look - will update soon

Best regards
Remy

**Comment by muryoh** [comment]
The reason this is happening is that by default, story.to.design imports your storybook on our servers which are Linux based

Unfortunately, after switching to Linux myself, I can see the storybook is not rendered properly as this is what someone on Linux will get:
![image](https://github.com/divriots/story-to-design/assets/1789748/cf11b95e-183a-42f9-8ce2-ed2c6df43ad4)

Because we use the sizes that are rendered in the browser to know how to layout components, we end up in that situation :disappointed: 

I see no font is actually specified in the source code for the component, meaning the browser/OS defaults to what it wants. Is this something that is expected on your side?

You could switch to using our [agent](https://story.to.design/docs/agent), as in that case the processing will happen on your machine locally, which I assume to be a MacOS machine as it was working fine for me on MacOS
But I would recommend we confirm the font situation first as it seems unexpected

Best regards
Remy

PS: If you would prefer discussing live don't hesitate to come over on [discord](https://story.to.design/chat), my username there is `remy.masson` :hugs:

**Comment by kimkisol** [comment]
Thank you for your response.

I think the font wasn't rendered properly in your environment because my components used Korean.
Changing the text language to English solved the layout distortion problem.
Is there any way I can get the component normal even if I use it in another language (e.g. Korean) in the plug-in?

And I would appreciate it if you could let me know what kind of rendering problems arise from Linux-based server.

**Comment by muryoh** [comment]
> I think the font wasn't rendered properly in your environment because my components used Korean.

Yes indeed, because my local OS did not have it installed

> Is there any way I can get the component normal even if I use it in another language (e.g. Korean) in the plug-in?

Unfortunately this is not possible, as we compute the layout based on various factors on our end. We would definitely consider adding that feature if it was necessary, but it is better for the general logic to be fixed and improved to avoid manual operations
The good news is that we are working on reworking that logic, in a way that better adapt to this use case. Here are the results I'm getting with said logic:


![image](https://github.com/divriots/story-to-design/assets/1789748/c48fdf59-86a9-4946-ab18-c8721bd798c2)


We should release it soon (1 to 2 weeks max but should be shorter)

> And I would appreciate it if you could let me know what kind of rendering problems arise from Linux-based server.

I cannot think of anything else but the fonts, however, our reworked logic should make up for it

A side question: are you not using webfonts (woff/woff2 fonts) on purpose? I can imagine that if your users are all Korean they will obviously all have Korean compatible fonts, however they will still get a different font based on their OS as MacOS/Windows/Linux all come with different fonts, while using webfonts would make up for it

Best regards
Remy

**Comment by kimkisol** [comment]
Thank you for following up on the issue quickly. Should I understand that once you release the reworking, other languages like Korean will also render properly?

Regarding the use of webfonts you mentioned in the side question, I will consider using them. Thank you.

**Comment by muryoh** [comment]
> Should I understand that once you release the reworking, other languages like Korean will also render properly?

Yes, it should, however it was not the original intended use for the rework, more like a consequence!

**Comment by muryoh** [comment]
We've released the autolayout revamp, it should work help in this situation!

Cheers
Remy
