### ISSUE TITLE
Open accordion

### ISSUE THREAD

**Issue by andreeeabb** [divriots/story-to-design#165]
## Describe the problem ##

---
Bug report identity: Please do not edit

Task path: WRqbNjeh3JQJI2q3UWHJ/2y0Lg6UBhOeKch64Kys9/lp6xq8tz85g0

**Comment by muryoh** [comment]
Hi @andreeeabb,

Quoting your previous comment on #164:

> I have for example also design for whole pages, for example product detail page. I have also there some accordions and want to show them open. (issue 165)
> If I choose from variants tap true it does not happen anything, so I suppose I have to use the advanced variants?

Yes indeed! Because the page contains a lot of elements, story.to.design does not know what element to interact with.

<hr/>

# TLDR

I realize I've provided a lot of information you may not want 😄 Here's a summary!

You can use the following configuration:
```
{
  "initArgs": {
    ":actionSelector": "#\\#main > section > div.main__content > div.ids-product-detail.container > div.ids-pdp__description > div > div.description.--border > div.button-wrapper > button"
  },
  "variantProperties": [
    ":tap"
  ]
}
```

<hr/>

# Why your current configuration does not work

I see your configuration here:
![image](https://github.com/divriots/story-to-design/assets/1789748/b915f448-01fa-4da7-9309-5a9fd417a5aa)

The problem is the following: there are many buttons matching that selector. We can see that by going to the developer tools while on your Storybook component:
![image](https://github.com/divriots/story-to-design/assets/1789748/9f547ae0-7c3d-4bf6-9697-31394fa35991)

Then, in the `Console` tab, inputing `document.querySelectorAll('.ids-button-link--ghost')` + Enter:
![image](https://github.com/divriots/story-to-design/assets/1789748/9f8843e2-c3cf-4e52-bb21-c6efe2c4eb9d)
 
Since there are 12, story.to.design cannot choose the correct one here, you need to help it a bit

<hr/>

# How to find the proper selector value

Here's a quick howto for the `:actionSelector`:

In the browser (I'm using Chrome here), right click on the element you want to interact with, and choose `Inspect`:
![image](https://github.com/divriots/story-to-design/assets/1789748/4d5dabb4-67ae-4365-8a03-2502ffc43027)

You should then see something like this:
![image](https://github.com/divriots/story-to-design/assets/1789748/4b31eb40-0c89-44eb-a8c7-6a2288d163e1)

(sometimes the browser will not select exactly the element you are interested in. It is best to try and select element that can be interacted with, like `button`s)

You can then right click in the tree and choose `Copy selector`:
![image](https://github.com/divriots/story-to-design/assets/1789748/c4494693-9d61-40e2-9b2d-a0119dca5706)

And finally, you just need to paste that value into the `:actionSelector`, giving (the `#` character has to be escaped, it is not very common to use one in element IDs):
```
{
  "initArgs": {
    ":actionSelector": "#\\#main > section > div.main__content > div.ids-product-detail.container > div.ids-pdp__description > div > div.description.--border > div.button-wrapper > button"
  },
  "variantProperties": [
    ":tap"
  ]
}
```

Importing your component should now expand the accordion (I imagine that was the one):



![image](https://github.com/divriots/story-to-design/assets/1789748/81d8f08d-5ddb-4e22-b6f6-2d6860d09884)
