### ISSUE TITLE
Table footer double border problem

### ISSUE THREAD

**Issue by dalexiev00** [divriots/story-to-design#176]
## Describe the problem ##

Hello,
I have noticed that we have 2 borders in the footer for a table - top one coming from the footer cells and bottom one from the cells above the footer. The double border doesn't occupy the whole line. 
I need help because I don't see what I could do on my side. I can share more info if needed.

---
Bug report identity: Please do not edit

Task path: ep257UoJEMTnEDJeFpEl/1bA1JLkLYX3xr40WMSdS/mltqihy0kslj

**Comment by gluck** [comment]
Hi @dalexiev00 ,

indeed this is caused by `border-collapse: collapse` CSS property being used.
We don't support this property yet, I'll have a look at the complexity of collapsing the borders manually before importing to figma, but no guarantee here.

You may be able to work around it by removing one of the borders which are collapsing in the DOM (e.g. `tbody:has(+tfoot) > tr:last-child > td { border: none; }` ) but I understand that's far from ideal.

Sorry about that.

**Comment by dalexiev00** [comment]
Alright, no worries, thanks for feedback!

**Comment by dalexiev00** [comment]
One more thing, could you check what's wrong with the font weight? it's not supposed to be that bold, I could open new issue if you need.
