### ISSUE TITLE
The font weight is not the correct one

### ISSUE THREAD

**Issue by dalexiev00** [divriots/story-to-design#180]
## Describe the problem ##

Hello, it's me again.
We have problem with the font-weight of the text. Th and Td Cells are not the same as what we have. And the problem is not only for the table but other components as well.
Could you check them as well, please? 🙏

---
Bug report identity: Please do not edit

Task path: ep257UoJEMTnEDJeFpEl/TQqm0csfOKONMqw0Wmmo/9uzt8k19v40ng

**Comment by muryoh** [comment]
Hi @dalexiev00, super sorry about the late feedback 🙏 

I had a look at your issue today, here's what I saw:
- your storybook uses the font `Poly Sans Qonto` in weight 400:
![image](https://github.com/divriots/story-to-design/assets/1789748/15064e16-b9d7-4e86-9d76-00a26f490595)
- on my machine, since I did not have your font installed, it originally resolved to `Inter` in Figma regular:
![image](https://github.com/divriots/story-to-design/assets/1789748/c02dd05b-0f8c-4481-9ad7-ecb6d341e0e1)
- after installing the font, it resolved properly in Figma:
![image](https://github.com/divriots/story-to-design/assets/1789748/3bf4a43e-bd53-4743-a5fa-ae667e667766)

Is this what you're seeing to, or are you seeing something different?

Best regards
Remy

**Comment by dalexiev00** [comment]
Hello 🙂 Thank you for your response!
I just installed the font locally and checked on figma. 
The font is the right one but for some reason I see it more bolded instead of being thinner font-weight. 
I see on your screenshots that it's okay which is very strange 😅
![image](https://github.com/divriots/story-to-design/assets/133855760/c1bb833d-c69b-4ec3-ae65-663db0b92250)

**Comment by muryoh** [comment]
I imagine we did not install exactly the same font, or you have more available than I do
In Figma, what other choices do you have other than `Bulky`?

**Comment by dalexiev00** [comment]
Aah yes, I installed more fonts, but in the storybook is thinner, no?
![image](https://github.com/divriots/story-to-design/assets/133855760/39d32fd1-69c3-4636-bd91-2b621f9eb5d6)

**Comment by muryoh** [comment]
Yes, I believe the problem is our mappings there
In the browser weights only as numbers
In Figma, you don't manipulate numbers, but style names

Which means we need to map them out - and I believe it's our first time seeing those style names, so we probably fallback to 400 instead of say 700 for `Bulky`

I cannot really test as I don't have the fonts, but I'm positive that would be the problem. I'll add the mappings for it and will let you know when to expect a release (best case would be today, worst case beginning of next week!) 👍

**Comment by dalexiev00** [comment]
Okay, that's perfect, thank you 👌

**Comment by muryoh** [comment]
One thing though, could you confirm the weights with me if you have them available, or somehow send me the fonts (could be on Discord at https://story.to.design/chat, my pseudo there is `remy.masson`)

I imagine
Slim => 100 or 200 or 300?
Neutral => 400
Median => 500?
Bulky => 700?

**Comment by muryoh** [comment]
nvm I think I found them - https://www.onlinewebfonts.com/fonts/polysans_qonto

**Comment by dalexiev00** [comment]
Oh, that's perfect

**Comment by muryoh** [comment]
So, fyi:
```
  Slim: 300,
  Neutral: 400,
  Median: 600,
  Bulky: 700,
```

**Comment by muryoh** [comment]
Hi @dalexiev00 ! Just released a new version of the story.to.design plugin
Just be sure to refresh your Figma tab if you had run the plugin before, then you should get the update on restart of the plugin

 Finally, hitting `Reset canvas` should allow the new mapping to be pulled 🤞 
![image](https://github.com/divriots/story-to-design/assets/1789748/d5882a43-cc8c-4f58-a56f-873dc7db1c7a)

Best regards,
Remy

**Comment by dalexiev00** [comment]
Hey, thank you for the update and work :) 
Only now I cannot use it on figma, it's stuck :/
![image](https://github.com/divriots/story-to-design/assets/133855760/68a6e481-7b73-45dd-80d8-4e2a74902f3e)

**Comment by muryoh** [comment]
😱 
I don't know what could be the problem, can you either come over on [Discord](https://story.to.design/chat) to so we can further investigate?

I think we'll need the agent logs to analyze

**Comment by dalexiev00** [comment]
Yes, of course :)
