### ISSUE TITLE
New component issue report

### ISSUE THREAD

**Issue by SunnyP** [divriots/story-to-design#182]
## Describe the problem ##

So I am importing again and again from local story book server however some components it shows are broken and I am not able to fix them. I restarted everything. 
<img width="472" alt="image" src="https://github.com/divriots/story-to-design/assets/3269171/71e28741-dcd7-4f31-9062-88eca3e9085b">

---
Bug report identity: Please do not edit

Task path: rBftRRDZIOHWmlGmLiuo/qyrRbevcrxEQCcIp7NyO/j64uvfy5zuig

**Comment by muryoh** [comment]
Hi @SunnyP !

For some reason we tried to open `http://127.0.0.1:49711/iframe.html?id=renderings-hero--static-1-item` but it could not be reached (this is what we captured in the report):
![image](https://github.com/divriots/story-to-design/assets/1789748/cdd23477-e045-4c1c-9f30-e946f65c537b)

That seems like a weird port since your screenshot shows you as connected to `http://127.0.0.1:8080`

Was your development server on port 49711 and you connected to it earlier switching to local mode? 

Feel free to reach us out on https://story.to.design/chat, otherwise we'll try and keep up here!

Best regards,
Remy
