### ISSUE TITLE
New component issue report

### ISSUE THREAD

**Issue by CJohanssonEpiroc** [divriots/story-to-design#184]
## Describe the problem ##
I am running into a reoccurring problem where it is importing incomplete components. Trying to import a progress bar, and it is importing an empty container on the canvas. Tried a few other components that as similar and have the same issue. Fragments or empty canvases. Thanks!

---
Bug report identity: Please do not edit

Task path: rsVFKG4ZgmGOq76pYUGV/y11aS20tac0IqcdLr5MH/r5vf16stnf2s

**Comment by muryoh** [comment]
Hi @CJohanssonEpiroc , having a look!

**Comment by muryoh** [comment]
Hey again! So, there are a few issues:
- you will need to set a viewport in order to capture this component. The reason is a bit complicated to explain, but basically in order to capture "auto layoutable" components, we force them to render as small as possible in the DOM, and in your case your component actually shrinks down to an empty element:
![image](https://github.com/divriots/story-to-design/assets/1789748/ebb05dde-ae72-4cfe-86cf-816a0b68667f)
You can just specify an viewport there, it will be the default size we import for that component:
![image](https://github.com/divriots/story-to-design/assets/1789748/faabb754-157d-492b-9f71-0b4638371d26)
- there were a couple bugs with the `progress` element that we were not supporting properly - we will release a new version soon fixing the bugs
- I noticed you have a `Switch UI` link hanging around. This is because it is rendered outside the `storybook` root, and we consider it may be a portal element (ie something that was opened on purpose outside the storybook root like a modal)
You can specify a [:portalSelector](https://story.to.design/docs/special-args#portalselector) to get rid of it, probably in the init configuration:
![image](https://github.com/divriots/story-to-design/assets/1789748/00e5f234-4b81-4b8d-82d1-7046a56def13)
Then specify something like this:
```
{
  "defaultImportConfiguration": {
    "initArgs": {
      ":portalSelector": ".portal-frame-class"
    }
  },
  "styleMapping": {}
}
```
Where `.portal-frame-class` is a selector to your portal (if any) or just something that does not exist so we won't find any portal element


Here's what it looks like after the configuration changes and the fixes I have locally:
![image](https://github.com/divriots/story-to-design/assets/1789748/61baf169-3084-4552-ac2b-9b9183873d89)

I'll let you know when it's released! 🚀 Probably in the next two days

Cheers
Remy

**Comment by muryoh** [comment]
Hi @CJohanssonEpiroc !

Sorry it took more than the mentioned 2 days, it's out
Be sure to update your agent too 🙏 

Cheers
Remy

**Comment by muryoh** [comment]
And to reopen if needed if my recommendations don't work/make sense to you!
