### ISSUE TITLE
New component issue report

### ISSUE THREAD

**Issue by higginbg** [divriots/story-to-design#197]
## Describe the problem ##

Component is not importing properly: https://mosaic-dev.saif.com/?path=/story/design-system-molecules-phoneinput--phone-input

What was imported:

<img width="534" alt="image" src="https://github.com/user-attachments/assets/bbd2d7f4-eb3b-44f6-9375-27351caae41a">

---
Bug report identity: Please do not edit

Task path: sPSi7PCYLq48jR1Xt8Y6/iRHJ1Y4DygckK9lVvLGc/lsr9ft12sat2f

**Comment by muryoh** [comment]
Hi @higginbg,

I just had a look: the problem happens because `countries` is a `list` argument. Unfortunately at the moment the UI considers it to be a `string`, so it's telling the component `countries is US` instead of telling it `countries is the list [US]`

I will put this in our backlog - in the meantime, you can use [advanced mode](https://story.to.design/docs/setup-variants-advanced) to set it up. Here's a simple example:

```
{
  "initArgs": {},
  "variantProperties": [
    ":tap",
    {
      "fromArg": "countries",
      "values": [
        {
          "argValue": [],
          "name": "all"
        },
        {
          "argValue": [
            "AC",
            "FR"
          ],
          "name": "AC and FR"
        }
      ]
    }
  ]
}
```

Yields the following:
![image](https://github.com/user-attachments/assets/43bb210f-fcee-4d41-afc3-86ebd4070fe2)


I noticed there currently is a problem with the input flag not showing up - I'm working on fixing it

Hope that works for you!

Best regards,
Remy

**Comment by higginbg** [comment]
@muryoh That works, thank you!

**Comment by muryoh** [comment]
Good to hear! Closing as there's a workaround - did add it to our backlog 🙏
