### ISSUE TITLE
Button isn't using nested icon component

### ISSUE THREAD

**Issue by katie-schmidt16** [divriots/story-to-design#200]
## Hi, I'm trying to get the icon within our button component to be a nest component. I've imported the icon component in the same file but when I import the button the icon is not a component. ##

---
Bug report identity: Please do not edit

Task path: hpPpNB3AXDmRHPrweEFJ/O9mdWr8t8Mik022ELj1i/1pnckst7jmvg6

**Comment by muryoh** [comment]
Hi @katie-schmidt16 

Sorry to hear that! I just checked - (sorry it's a bit technical) it does not work because an additional element is added between the storybook root element and the actual element:

![image](https://github.com/user-attachments/assets/1b9b91a0-8ed2-4c9f-a3ab-017a0460c983)

This element does not have the same size as the actual component element:
![image](https://github.com/user-attachments/assets/402f5ef0-2e9c-4bdf-a12a-f75a5ac96ea9)

vs 

![image](https://github.com/user-attachments/assets/3a32efa9-c4ad-4bae-b02d-4cfdef2c2ba2)

So we currently capture that "additional element" without affording to cut it out because in other situations that's what is actually expected


There are two immediate solutions

# story.to.design workaround

You can instruct story.to.design to capture the specific icon element
In order to do that, you will need to change your icon component to advanced mode and specify `":selector": "#root-inner > div > kmk-icon"` in the `initArgs` section
Here's an example:

```
{
  "initArgs": {
    ":selector": "#root-inner > div > kmk-icon"
  },
  "variantProperties": [
    "name",
    "color",
    "size"
  ]
}
```

After updating the icon component, you will need to also use the `Reset canvas` on the button component to retrigger subcomponent detection:
![image](https://github.com/user-attachments/assets/e646c8a3-bab7-49ca-b5d9-131c2835dd79)

# Directly modifying the storybook

You could ask the developers to modify the sizing of that additional element so that it directly fits the size of the icon component element. This could be achieved by adding for example `display: inline-flex` to that element, or `display: contents`:
![image](https://github.com/user-attachments/assets/69e3183c-8e1c-4c30-b6ff-85b3a62800f4)

After modifying this, you would need to update the icon component then reset the button one as instructed for the first solution

I hope that helps!

Cheers,
Remy

**Comment by katie-schmidt16** [comment]
Ok I did get that to work. I think I already know the answer to this but I want to confirm. When I import icons with the color and size options, there are 1,000s of variants. If I leave these options out there is a more manageable number of variants but then the component isn't nested in other components such as the button by default. Is that correct?

**Comment by muryoh** [comment]
> Ok I did get that to work. I think I already know the answer to this but I want to confirm. When I import icons with the color and size options, there are 1,000s of variants. If I leave these options out there is a more manageable number of variants but then the component isn't nested in other components such as the button by default. Is that correct?

Yes, in order to be able to nest a component A into a component B and have the 1000 variants of component A accessible, we need to be able to:
- find an exact match of one of the variants of component A instance into component B (so if component B uses icon `danger` but you imported all variants but `danger`, it will not work)
- have the 1000 variants of that component A imported, so we can switch to them on component B

Closing for cleanup, I hope that helped!
