### ISSUE TITLE
New component issue report

### ISSUE THREAD

**Issue by iamluisro** [divriots/story-to-design#42]
## Describe the problem ##
Attempting to import a Modal from react-bootstrap, but story2design fails. 

---
Bug report identity: Please do not edit

Task path: BwIZ8sIC6SszE38SZFMm/LkkHL5JbKn3LwflpyzIg/uqohh7upe9gh

**Comment by muryoh** [comment]
Hi @iamluisro! Unfortunately the report cannot be read, I believe because the storybook is in dev mode which at the moment is not supported when reporting issues

Could you re-report your issue with the built storybook? Feel free to ping us on Discord if you'd prefer to discuss it there

Cheers,
Rémy

**Comment by muryoh** [comment]
I'll be closing this in the meantime, don't hesitate to reopen it whenever you have new feedback :pray: 

Cheers
