### ISSUE TITLE
New component issue report

### ISSUE THREAD

**Issue by alextsayun** [divriots/story-to-design#43]
## Describe the problem ##

I can't import any of the components from storybook.

---
Bug report identity: Please do not edit

Task path: 3R3nHaGiGca1AQe9uWyz/mNs6Xw9kDfwLbtrCcYix/sshbcs1qoafre

**Comment by gluck** [comment]
Hi @alextsayun , sorry to hear that.
This is caused by the `Preview` root component/div which is absolutely positioned.
It causes the `#root` div size to be empty, so story.to.design thinks there's nothing to import.
We'll fix it to import children anyway in that case, but you may want to revisit this part of your storybook.
I'll keep you updated on progress.

**Comment by alextsayun** [comment]
Thank you, will check!

**Comment by muryoh** [comment]
Hi there,

Are you still having the problem?
As mentioned, that absolute positioning on the root element can be a problem. 2 alternatives:
- use [advanced mode](https://story.to.design/docs/setup-variants-advanced) and more specifically the `:selector` meta arg which allows you to specify which element (through a CSS selector) is to be extracted by story.to.design
- that one isn't available yet, but we were considering adding a default global `:selector` support

Don't hesitate to reach out on Discord if you need help (Remy#5067 on https://story.to.design/chat)

Cheers!
Rémy
