### ISSUE TITLE
Components are imported with right padding

### ISSUE THREAD

**Issue by VoloDziuKoho** [divriots/story-to-design#50]
## Describe the problem ##

I am importing a simple "chip" component with a few properties in it. The plugin imports component with extra padding on the right, which makes it not very usable in Figma. The component in Storybook does not have that padding, so not quite sure where it's coming from

<img width="222" alt="Screenshot 2023-02-23 at 9 09 15 AM" src="https://user-images.githubusercontent.com/79857391/220931273-01fa29c6-31ea-4f06-96ec-27f31fc93f23.png">
<img width="809" alt="Screenshot 2023-02-23 at 9 10 40 AM" src="https://user-images.githubusercontent.com/79857391/220931582-7ac5dd9e-db06-45d5-a847-7c693182addf.png">

---
Bug report identity: Please do not edit

Task path: Dlispy0XNKMa6bQDHNHV/a7cxtKxZoABfzh6dJPLu/qc2c811daurkc

**Comment by muryoh** [comment]
We should be releasing a fix for it soon! :rocket:

**Comment by muryoh** [comment]
Should have been fixed in the last release last week!
The problem came from story.to.design, not "zooming in" enough in some cases when importing components (because the enclosing elements take the full width of the page in HTML, so we need to adapt those widths to the actual component width)

Cheers!
