### ISSUE TITLE
Padding and size of Figma component does not match that in the story

### ISSUE THREAD

**Issue by VoloDziuKoho** [divriots/story-to-design#52]
## Describe the problem ##

The coded component has 24px height (18px line-height + 2px top & 4px bottom padding + 1px border top & bottom), however, the component in Figma ends up 26px high.

Similarly, the vertical padding of the Figma component ends up being 2.5px & 5.5px instead of 2px and 4px.

Overall, the Figma component looks "close", but differences are noticeable and would be a blocker for our design team if we wanted to adopt the plugin

---
Bug report identity: Please do not edit

Task path: Dlispy0XNKMa6bQDHNHV/CosLurtdg9Yzd8VnrMUA/15o87jn6qtm45

**Comment by muryoh** [comment]
Hi @VoloDziuKoho !

We just released a new version of the agent that should fix this issue (your agent should prompt your to update on restart). From our investigation it seems to be caused by display scaling on hidpi/retina displays, which would throw off our text position computations

The top/bottom paddings should now be as expected. Note, however, that the horizontal padding may still present inconsistencies because Figma does not compute the text element width the same way, offsetting it for some reason (rounding?) from 26.xx px to 27px - which may explain why you see a smaller right padding

I hope your issue will be solved with this release

Cheers
Rémy
