### ISSUE TITLE
Text child generates multiple nodes

### ISSUE THREAD

**Issue by okonet** [divriots/story-to-design#65]
I have a component that renders one paragraph element. After importing it, I see 3 different text nodes each one for each line. This makes the component not usable for text purposes.

I expect a component where I have my text node that is editable with proper styles applied to it.

---
Bug report identity: Please do not edit

Task path: A180IkCIjkpoihHcop0Y/EQKzvhi6cT82Fwvpk2fN/gyieyc06ebs

**Comment by gluck** [comment]
Hi @okonet,

while we were previously merging paragraphs (as you expect), we had to revert it because many HTML inline paragraph can't be represented as a figma paragraph (if the paragraph contains anything non-text, e.g. images, SVGs, inline blocks etc.).
We need to sort out the proper logic, so that simple text paragraphs are merged, but complex ones are left un-touched, to respect their intended layout.

I'll keep you updated when it's done.

Thanks for the report.

**Comment by gqio** [comment]
Fixed
