### ISSUE TITLE
New component issue report

### ISSUE THREAD

**Issue by elenabraeutigam** [divriots/story-to-design#70]
## Describe the problem ##

I always get an error trying to import this component:

<img width="436" alt="Screenshot 2023-05-02 at 10 17 52" src="https://user-images.githubusercontent.com/129752452/235615397-b5feb36c-d070-4a68-b36c-3e2ca59745a2.png">

I tried leaving out different variants, but the import still fails every time.
I don't have this issue with any other components.

---
Bug report identity: Please do not edit

Task path: 3ha6WtaKf2ON2Bf0HK24/FyW2bahh3rNxdSSi1pn4/xxpruh1ne8dvo

**Comment by muryoh** [comment]
Hi @elenabraeutigam, sorry for the trouble!

Indeed - there is an error here because story.to.design cannot find the component to extract
The storybook root div is empty:
![image](https://user-images.githubusercontent.com/1789748/235689488-85cac01e-9ebf-4df4-8dd0-ce4bd5b7057f.png)

This happens because this is a special component - a modal which renders its content in a different div that the standard one:
![image](https://user-images.githubusercontent.com/1789748/235689729-19b3a336-2651-4d48-b556-5acd9a803ebf.png)

In that situation, you currently need to switch to [advanced mode](https://story.to.design/docs/setup-variants-advanced) and use the [:selector](https://story.to.design/docs/variant-properties-api#selector) to specify what to capture with a CSS selector

Here's a sample configuration, based on yours, which should yield something close to what you expect:
```
{
  "initArgs": {
    ":selector": "body > div[role='presentation'] > div[role='presentation'] > div[role='dialog']"
  },
  "variantProperties": [
    "theme",
    ":hover",
    ":tap",
    ":active",
    "contentWidth"
  ]
}
```
All of the configuration but the `:selector` part was created from your existing configuration

Note that you may hit a similar problem with the simulated args - ie `:hover`, `:tab` and `:active`: those arguments will have story.to.design simulate an action on an element, however it basically tries to find the first "actionable" element which may not be what you want. This is where [:actionSelector](https://story.to.design/docs/variant-properties-api#actionselector) comes in handy

You could then use the following configuration:
```
{
  "initArgs": {
    ":selector": "body > div[role='presentation'] > div[role='presentation'] > div[role='dialog']",
    ":actionSelector": ".MuiDialogActions-root button:nth-of-type(1)"
  },
  "variantProperties": [
    "theme",
    ":hover",
    ":tap",
    ":active",
    "contentWidth"
  ]
}
```
Which tells story.to.design to use the first button of the element with class `MuiDialogActions-root` to simulate actions

I hope this helps

Cheers,
Remy
