### ISSUE TITLE
Textfield label: positioning is off, label is cutoff

### ISSUE THREAD

**Issue by nils-rohe** [divriots/story-to-design#79]
This has multiple issues: 

1. 
This is how the component looks in Storybook:
![image](https://github.com/divriots/story-to-design/assets/108518250/36e3fc5b-066c-4ea1-b27c-3f90fbc4e4b2)

After import to Figma it looks like this: 
![image](https://github.com/divriots/story-to-design/assets/108518250/d87aec87-f001-4f1f-b229-bcc01771f70c)

2.
Additionally, the component resizes if it is set to "multiline": 
![image](https://github.com/divriots/story-to-design/assets/108518250/79c677a1-beb8-4b3f-8fbe-d8823242abe1)

If it is not multiline it stays the same size:
![image](https://github.com/divriots/story-to-design/assets/108518250/c0ff1234-3855-4e16-9f29-40c384784ca0)

3. If in Figma the Textfield is made required, it is not possible anymore to change the label.. the option disappears in the sidebar. This is possible in storybook though.

4. If the type is set to date, there is an Input field: 
![image](https://github.com/divriots/story-to-design/assets/108518250/1f83a148-000d-44ce-8882-1a3fd78b666d)

If it is set to text there is none:
![image](https://github.com/divriots/story-to-design/assets/108518250/8a5ccf3c-b57e-49cd-a224-f8eb36b55661)

Hope you can help with that! Thank you!
---
Bug report identity: Please do not edit

Task path: 3ha6WtaKf2ON2Bf0HK24/muRGQf71D35XMfT4tac9/1crm89n1qt4az7

**Comment by muryoh** [comment]
Quite the challenging component :)

1. <fieldset> elements have a very special behavior in browsers, will look into improving that
2. Yes we've identified a few corner cases where this happens - it's in the pipe!
3. Indeed, will see what can be done
4. Yep - If you had a placeholder there, we would definitely map it and it would end up in Figma. But currently we see an empty node and just "skip it". We could look into adding an empty placeholder ourselves there
5. (bonus) Noticed the icons were missing, will release a fix for it too (we were not supporting [image-set](https://developer.mozilla.org/en-US/docs/Web/CSS/image/image-set))

**Comment by nils-rohe** [comment]
Thanks for the feedback, looking forward for the fixes :) 
Actually, our components are mostly just wrapped MUI components.. so I am afraid we will have more of these challenges coming up for you 🙈

**Comment by gqio** [comment]
Hello @nils-rohe 

1- it's solved minus the fact of the border going through the text. Still investigating for this and using the subtract rectangle.
2- solved
3- solved
4- What is really hard here is that there is no Text node here inside the input even with deep inspect 
![image](https://github.com/divriots/story-to-design/assets/1063530/32d29c85-5185-4c45-a28a-048727420151)

I will see for the 4# what we can do (like generating / infering an empty text node even it's a empty div at the DOM level) but I think it's not gonna happen soon because of the holidays and reduced team.
Could you please reopen a ticket with just only this story and this variant ? (just need to import with less properties and report)

Best
