### ISSUE TITLE
material-ui/Alert: Text growing in wrong direction; Container not resizing

### ISSUE THREAD

**Issue by alexandergrot** [divriots/story-to-design#86]
hey all,

for the [material-ui/Alert](https://mui.com/material-ui/react-alert/) component the content of the `Alert` component seems to grow in the wrong direction and at least the outer container seems to not grow with the given content.

storybook component with example content:
![grafik](https://github.com/divriots/story-to-design/assets/102791744/55542e3b-a6a1-4486-87c8-a4c1f7714df9)

component imported to figma and changed content text:
![grafik](https://github.com/divriots/story-to-design/assets/102791744/a457cc81-fdf8-417b-a087-15a0328d236f)

---
Bug report identity: Please do not edit

Task path: 3ha6WtaKf2ON2Bf0HK24/cTJHZkeCJCNZ1kgqi46Q/ptho55ubujt5

**Comment by gqio** [comment]
Hello @alexandergrot 

Yes apparently we need to fix this constraint algo in this case.
Having margin auto in a flex is something apparently we do not support correctly.
I am checking and I will keep you posted

Best

**Comment by gqio** [comment]
Hello @alexandergrot 

We fixed the issue for the resizing.
A fix for the multiline will follow in the next release.

Best

**Comment by alexandergrot** [comment]
hey @gqio 

Thanks for the always quick and great support!

**Comment by gqio** [comment]
Hello @alexandergrot 

Just for keeping you updated.
We fixed some stuff in our algo for constraints and sizing mode.

But here we are facing some roadblocks with this component.
It (the action inside this alert) uses margin-left:auto inside a flex container (and a negative margin-right)
The way Figma works for autolayout is with border-box sizing and there is no margin in Figma only padding/gap.
So basically we can't do autolayout here, because of mixed padding.

We are currently investigating 2 solutions for making it happen, either with a metaframe around the action component to represent the margin-box (this one seems the right one but needs more time to rework our algo), or by adding a spacer inside this autolayout (this one has a drawback of non collapsible padding like margin collapsing inside the browser)

We will keep you posted.

Best.
