### ISSUE TITLE
Button hover visual change not reflected in figma

### ISSUE THREAD

**Issue by alexandergrot** [divriots/story-to-design#88]
hey all,
the story we imported to figma is basically just a special variant of [material-ui/Button](https://mui.com/material-ui/react-button/). when imported to figma the `hover`, `tap` and `active` state dont show visual differences as it does in storybook.

`hover` example in storybook:
![grafik](https://github.com/divriots/story-to-design/assets/102791744/87eac5c7-fbf1-45c7-81da-968bc9453049)

imported to figma:
![grafik](https://github.com/divriots/story-to-design/assets/102791744/780ce537-ebbb-45f6-a828-9ccdea03e90c)

---
Bug report identity: Please do not edit

Task path: 3ha6WtaKf2ON2Bf0HK24/MqMtAjToG0l8Uxna4ZNc/1dzdaoqqchgm9

**Comment by muryoh** [comment]
Hi @alexandergrot , having a look
Our current logic is failing to find anything to action on (button, input,...)
There's an input in that component but it's hidden, making it hard to know what to action on!

On it :)

**Comment by muryoh** [comment]
Will push a fix for it
In the meantime, if you want to, you can switch to `Advanced Mode` and use the [:actionSelector](https://story.to.design/docs/special-args#actionselector) arg

This one basically tells story.to.design what element to interact with instead of letting it try to figure out which element to use
I believe in your case the configuration could look like this:
![image](https://github.com/divriots/story-to-design/assets/1789748/adcf246a-f2af-4516-b8d5-d31c965686c8)

```
{
  "initArgs": {
    ":actionSelector": "#storybook-root > label"
  },
  "variantProperties": [
    ":tap",
    ":active",
    ":hover"
  ]
}
```

**Comment by alexandergrot** [comment]
thanks alot @muryoh, will try that :)
