### ISSUE TITLE
Interaction with component creates new DOM items that aren't captured by plugin

### ISSUE THREAD

**Issue by chungsi** [divriots/story-to-design#94]
## Describe the problem ##

Discord thread: https://discord.com/channels/744781525119139859/941696848534597632/1138582278868578377

We have some components that have select dropdowns in them, and design wants to see a state when the dropdown is opened. At the moment, the :active flag variant on the component will trigger a chevron icon to change directions (correctly) but without the dropdown opened.
![image](https://github.com/divriots/story-to-design/assets/14225300/0fffa45a-3d93-4201-afca-bc5198293529)

In the code, when the dropdown in activated, a new DOM item is created outside of the Storybook root. (Below, `<div role="presentation" id="menu-" class="MuiPopover-root ..." />`
![image](https://github.com/divriots/story-to-design/assets/14225300/22255e1c-a206-4505-b94c-46dd113ae2ae)

Also, the reported component has failing variants (weren't failing before) but I'm not too concerned about that so no need to debug those. I think they're due to the state imports (like with `:active`), so probably related to/will be resolved by my above question.

---
Bug report identity: Please do not edit

Task path: R702fkgNoAQvwSdKueSF/n4FEfXIzxS9ccrXeP04G/jt4pexr77pi2

**Comment by muryoh** [comment]
Hi and thanks for the report!

We've just released a new version of story.to.design with the added support of [:portalSelector](https://story.to.design/docs/special-args#portalselector)!

You can either set it in advanced mode, for a single imported component, or set it in the default configuration so that story.to.design will always look for those additional elements

Note that there may be some hiccups with sizes/positioning when resizing because DOM wise there is no actual relationship between those elements 

I hope it helps fixing the problem you've seen, don't hesitate to reopen if it doesn't

Cheers
Remy
