### ISSUE TITLE
Text/Container doesn't grow as expected if content changes

### ISSUE THREAD

**Issue by alexandergrot** [divriots/story-to-design#96]
hey all,

the problem with this component is, that if you change the texts, the outer container doesn't grow as expected which leads to those 2 scenarios:

1:
![grafik](https://github.com/divriots/story-to-design/assets/102791744/e8b4d82a-122a-4a43-abad-1ed537a231f1)
for the title the text grows to both sides. expected is that it grows to the right

2:
![grafik](https://github.com/divriots/story-to-design/assets/102791744/f2f41005-150d-47bb-858e-9a1a247791f4)
the container containing the cotnent text keeps the same length but grows up and down

---
Bug report identity: Please do not edit

Task path: 3ha6WtaKf2ON2Bf0HK24/cTJHZkeCJCNZ1kgqi46Q/ay09al1l9y613

**Comment by gqio** [comment]
Hello @alexandergrot 

Not sure why it's done like this
![image](https://github.com/divriots/story-to-design/assets/1063530/69af6636-51eb-4adc-bb53-d8af76e85760)
There is no margin concept in figma, only gap or padding.
The way we are doing the transformation here is we detect a margin-box taking all the space inside this flex container.
That way it's reflecting in Figma like this.
![image](https://github.com/divriots/story-to-design/assets/1063530/b542a306-8ea8-410c-92c5-eb37f11e34b9)
And because it's a margin auto (not linked to a flex container like flex-grow) we determine the size of the second block to be a fixed size.

Here we could do better I think with using hug and not fixed for the second block, it will support then the resize correctly 
![image](https://github.com/divriots/story-to-design/assets/1063530/4d0151e3-781a-40c8-ac3a-f0971655927c)

I will keep you posted 🙏

**Comment by gqio** [comment]
Fixed with the last release
